apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-example
  template:
    metadata:
      labels:
        app: cassandra-example
    spec:
      containers:
      - name: cassandra-example
        image: cassandra-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-example
  namespace: default
spec:
  type: NodePort
  selector:
    app: cassandra-example
  ports:
  - port: 80
    targetPort: 8084
    nodePort: 30001
    protocol: TCP
