spring:
  data:
    cassandra:
      keyspace-name: myKeyspace
      contact-points: cassandra
      schema-action: CREATE_IF_NOT_EXISTS
      port: 9042
      
server:
  port: 8084
  
logging:
  level:
    com.ssinghal: DEBUG